name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Lua 5.4
        uses: leafo/gh-actions-lua@v10
        with:
          lua-version: "5.4"

      - name: Set up LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install luacheck
        run: luarocks install luacheck

      - name: Lua syntax check
        run: lua -p obsidian-todos.lua

      - name: Run luacheck
        run: luacheck obsidian-todos.lua
